server:
  port: 8181
spring:
  kafka:
    bootstrap-servers: "localhost:19092"
    integer-serializer: org.apache.kafka.common.serialization.IntegerSerializer
    string-serializer: org.apache.kafka.common.serialization.StringSerializer
    json-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    avro-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    schema-registry-url : "http://localhost:8081"




